# This is a basic workflow to help you get started with Actions

name: Web | Build and Deploy - cache
on:
  # ONLY triggers on master branch
  repository_dispatch:
    types: [web-build-deploy]
  push:
    branches: main
    paths:
      - web/**
jobs:
  web-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn workspace sanity-gatsby-portfolio-web install
      - run: yarn test
