# This is a basic workflow to help you get started with Actions

name: Web | Build and Deploy - cache
on:
  # ONLY triggers on master branch
  repository_dispatch:
    types: [web-build-deploy]
  push:
    branches: main
    paths:
      - web/**
jobs:
  web-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          echo '::debug::deps cache miss - installing deps'
          yarn workspace sanity-gatsby-portfolio-web install
      - name: Build Website
        run: yarn workspace sanity-gatsby-portfolio-web build
